### PR TITLE
update: remove non-ethereum moonbeam->x channel from production

### PR DESCRIPTION
**Pull request by lattejed**
This removes the moonbeam->xdai channel from production as it's no longer needed

### CODE REVIEW

**Review by prestwich — COMMENTED** [review]
lgtm

**Comment by lattejed** [comment]
I've updated this to include the removal of all non-ethereum<-moonbeam channels

**Review by prestwich — COMMENTED** [review]
LGTM

**Review by prestwich — DISMISSED** [review]

**Review by rswanson — APPROVED** [review]
🦢

**Pull request merged**
